ALTER TABLE SISVENVI.T_VUDM_DOCUMENTO_ANEXO ADD ESTADO_ANEXO NUMBER(1,0) NULL;
ALTER TABLE SISVENVI.T_VUDM_DOCUMENTO_ANEXO ADD ID_ANEXO VARCHAR2(20) NULL;

UPDATE SISVENVI.T_VUDM_DOCUMENTO_ANEXO SET ESTADO_ANEXO =1;
